### ISSUE TITLE
Tuple should equal record

### ISSUE THREAD

**Issue by julianhyde** [julianhyde/morel#14]
A tuple with 3 fields should be of the same type as a record with fields named "1", "2", "3":
```
./morel
= (1, true, "yes") = {1 = 1, 2 = true, 3 = "yes"};
java.lang.RuntimeException: Cannot deduce type: conflict: tuple(int, bool, string) vs record:1:2:3(T6, T7, T8)
	at net.hydromatic.morel.compile.TypeResolver.deduceType_(TypeResolver.java:114)
	at net.hydromatic.morel.compile.TypeResolver.deduceType(TypeResolver.java:91)
	at net.hydromatic.morel.compile.Compiles.prepareDecl(Compiles.java:89)
	at net.hydromatic.morel.compile.Compiles.prepareStatement(Compiles.java:79)
	at net.hydromatic.morel.Shell.run(Shell.java:249)
	at net.hydromatic.morel.Shell.main(Shell.java:75)
```

**Comment by julianhyde** [comment]
Fixed in 4b9ddf5a061f4510aa181127a1a404eba366adae.
